### ISSUE TITLE
License

### ISSUE THREAD

**Issue by spk** [sitevalidator/nu-cat#1]
This repo is missing a license
Cheers

**Comment by spk** [comment]
Hi @jaimeiniesta 
I would like to use and contribute to this project but there is currently [no license](https://choosealicense.com/no-license/)
Do you consider using an opensource license ?
Thanks

**Comment by jaimeiniesta** [comment]
Sorry @spk - I missed your issue on November. Sure, I'll add an open source license.

**Comment by jaimeiniesta** [comment]
Done! Thanks @spk :)
